### ISSUE TITLE
Did not find most variables declared in RDDI example

### ISSUE THREAD

**Issue by umesh4b4** [x893/CMSIS-DAP#10]
Hi,

I did not find most number of variables declared in RDDI example RDDI_DAP_IF.cpp file  given in CMSIS-DAP-> RDDI->Example. However I have solved with few variables and macros. I could not find below variables, macros and data types.

1. MonConf.Opt 
2. PORT_SW
3. RWPage
4. TRNMODE
5. TRNVERIFY
6. DBG_Addr
7. RgARMCM
8. RgARMFPU

Regards

Umesh

**Comment by x893** [comment]
Ask about on ARM forum. RDDI... not changed from original ARM files.
