### ISSUE TITLE
USB devices are not recognized

### ISSUE THREAD

**Issue by HareGun** [x893/CMSIS-DAP#11]
I want to make a CMSIS DAP using CMSIS 5.1.0. I built a new project in line with KEIL's official website. Part of the DAP was added, but he didn't work. Can you help me with this problem? Thanks very much.

http://www.keil.com/pack/doc/CMSIS/DAP/html/group__DAP__ConfigUSB__gr.html

**Comment by bowman85** [comment]
I can recomended to use this lib.  https://stm32f4-discovery.net/2014/05/all-stm32f429-libraries-at-one-place/

**Comment by HareGun** [comment]
Thanks.But I'm using STM32F1. I've also tried to configure only the USB and RTX sections without DAP (adding the USB connection function to the main function). My computer is still hard to recognize. The D+ pin has a pull-up resistor.
