### ISSUE TITLE
When compiled HID device is not recognised by the system. 

### ISSUE THREAD

**Issue by diymat** [x893/CMSIS-DAP#12]
Hi. Just a quick question-maybe you know. When I flash the stm32F103 with the .hex file provided - everything is ok, when I compile it myself only CDC device is recognised. Do you have any clues?

**Comment by x893** [comment]
You're change any settings (optimization or other) ?
Can you check with debugger ?

**Comment by diymat** [comment]
No, I have just cloned it and opened in the free version of Keil (I do not use Keil). I can debug of course

**Comment by x893** [comment]
Project from github use F102 processor settings. May be need switch to correct version V1..V3 and F103 processor. Please check project settings for your board.

**Comment by diymat** [comment]
I have changed the uC of course.  But where is the version?

**Comment by diymat** [comment]
Recompiled - checked all the uC settings and the effect is the same -  VCOM is detected, HID is not. When I flash the provided HEX file it detects both :)

**Comment by x893** [comment]
What's hex you flash ?

CMSIS-DAP-V1-F103.hex
CMSIS-DAP-V2-F103.hex
CMSIS-DAP-V3-F103.hex

**Comment by diymat** [comment]
just flashed all of them. All provide both devices. The compiled version is not and to be stranger it detects as a different COM port which indicates some differences between descriptors sent.

**Comment by x893** [comment]
Select configuration in tollbar combo box (near Download toolbar button).
Also check pins in DAP_Config.h for your board.

**Comment by diymat** [comment]
As I wrote I do not know Keil :) and I did not noticed this toolbar. But unfortunately free version does not allow me to link the MDK

**Comment by diymat** [comment]
Thank you very much for your support.

**Comment by x893** [comment]
Can you check DAP_Config.h for your board ?
You can open it in vim/nano/notepad and define configuration.
Also you can flash hex files and see correct hex for your board (USB and SWD/SWC/JTAG pins configuration) or add schematic of your board here and i see in depth.

**Comment by diymat** [comment]
Hi. Thank you very much. Actually I  have everything I need.  I develop a board with DAP - so I just wanted to go through the existing implementation to do not reinvent the wheel. It is a STM32F3 board with many other interfaces on it. I honestly appreciate your help.

**Comment by x893** [comment]
No problem.
