### ISSUE TITLE
Can't install HID driver for F103 v2

### ISSUE THREAD

**Issue by steevenlee** [x893/CMSIS-DAP#4]
I'm using MDK5 + CMSIS_DAP_USB project, set reconfiguration to V2, both HID and CDC are enabled, from test, only CDC are properly installed on Windows7 32 bit version. HID can't be recognized. 

If I disable CDC in usb_config.c, HID can be auto recognized w/o installing any driver.

Finally I got it worked by changing VID/PID to official one and install driver from mbed, it will identify HID driver, then, install inf for CDC ACM.

**Comment by x893** [comment]
For HID no need any driver under Windows 7. I use 64 bit version and never have problem.

**Comment by steevenlee** [comment]
Try it on a new desktop :)
