### ISSUE TITLE
How about merge back this project back to master?

### ISSUE THREAD

**Issue by steevenlee** [x893/CMSIS-DAP#5]
I love your work, STM32 is popular... is there license issue if I give this a try?

**Comment by x893** [comment]
CMSIS-DAP codes initially provide by ARM

**Comment by steevenlee** [comment]
I found a big issue to merge SMT32 support to official branch: stm32f10x only support 8 endpoints, for a complete feature support, need 3+2+2 for CDC+MSC+HID, plus endpoint 0, is it possible to support them all?

**Comment by x893** [comment]
i never use this combination only HID + CDC but you can try
