### ISSUE TITLE
ST-LinkV2 nRESET pin

### ISSUE THREAD

**Issue by siorpaes** [x893/CMSIS-DAP#8]
Hello,

I tried CMSIS-DAP on ST-LinkV2 dongle using Keil but found some issues with nRESET signal: the target could not reset nor I could use the "attach under reset" debugger option. The logic analyzer could not see any activity on this signal either.
I checked where the nRESET pin is connected on this board and sorted out that it is hooked to PB6 (Pin 42), and not PB0 as reported in the code.

I changed to correct pin and now it's working like a charm. Is the dongle I have yet a different hardware version ? Or is there actually a minor bug in the code ?

Thanks for your attention

Regards,

David S.

**Comment by x893** [comment]
Hello,
I have various version of dongle - so may be make a mistake.
I'll review and fix

**Comment by siorpaes** [comment]
All right, thanks! let me know if you need any further information, esp on the dongle's hardware

**Comment by x893** [comment]
I check ST-Link V2 schematic (from NUCLEO board) and see PB0 for T_NRST signal. PB6 used for SWM_RST (for SWIM protocol)

**Comment by siorpaes** [comment]
Yes, you are correct: the schematic of Nucleo and Discovery boards do have NRST routed to PB0. However, the RST signal of the ST-LinkV2 dongle I have is connected to PB6. I triple checked continuity with multimeter. Could you verify on yours ?

![st-linkv2](https://cloud.githubusercontent.com/assets/1059507/12376709/ff74072e-bd02-11e5-89e1-6b9d8f7a6b92.png)

**Comment by x893** [comment]
I havn't V2 version but you can make new configuration STLINKV2 and make changes for nRST. Later send pull request. I can do this myself but later. :)
